### ISSUE TITLE
有兴趣加入你们的组织

### ISSUE THREAD

**Issue by xiaoweiChen** [CnTransGroup/discussion#3]
我这边自己已经翻译了很多书籍，还有一些准备好，但未翻译的英文书籍。
目前主要着重于C++和CMake。

想了解一下，若是在组织的库中进行译书，翻译库可以有另一份个人公开库或个人私有库么？

**Comment by y1yang0** [comment]
Hi @xiaoweiChen, 欢迎你的加入。你可以自由选择创建一份个人公开/私有库。在CnTransGroup中的翻译项目建议和其他项目风格保持一致（即，使用markdown，使用mdbook创建在线预览，README.MD格式保持一致等），你可以创建项目的时候选择EffectiveModernCPPChinese作为模板仓库：
![image](https://user-images.githubusercontent.com/5010047/209747000-822c45cc-b2c7-41d3-996e-85c137636c06.png)

**Comment by xiaoweiChen** [comment]
感谢回复！

貌似目前还没有加入组织，无法在组织下面创建库。
![Screenshot 2022-12-28 104549](https://user-images.githubusercontent.com/2756670/209749347-2eea05e3-04fb-4f8a-9647-362cfbaf69c4.png)

**Comment by y1yang0** [comment]
已经邀请～

**Comment by xiaoweiChen** [comment]
ヽ(*^ｰ^)人(^ｰ^*)ノ
